### ISSUE TITLE
Build Errors SHA - 78def1e893a1fdad14a48988902e24382d8fa483

### ISSUE THREAD

**Issue by redevill** [vyakymenko/angular-seed-express#142]
[ x] bug report => search github for a similar issue or PR before submitting
I'd be happy to do a pull request, but would need guidance on the procedure...

First error is obvious - line 14 defines _clientDir as a constant set to dev. Then in the production section line 68, it tries to reset it to prod.
_src/server/index.ts(68,5): error TS2540: Cannot assign to '_clientDir' because it is a constant or a read-only property._

Second error - Perhaps a typecheck line 96? as per this: https://stackoverflow.com/questions/30621139/typescript-union-type-not-working
_src/server/index.ts(97,37): error TS2339: Property 'port' does not exist on type 'string | AddressInfo'._

The last errors, seem to be addressed by this - https://github.com/angular/angular/issues/24245
_node_modules/@types/node/index.d.ts(167,14): error TS2687: All declarations of 'observable' must have identical modifiers.
node_modules/rxjs/internal/symbol/observable.d.ts(4,9): error TS2687: All declarations of 'observable' must have identical modifiers._

**Current behavior**
download the latest code and do: npm start
During the build there are 4 errors listed.

**Expected behavior**
the app should build and run without error.

**Please tell us about your environment:**

Running the seed project under webstorm with tsc 2.3.4

* **Angular Seed Version:** 
78def1e893a1fdad14a48988902e24382d8fa483

* **Node:** `node --version` =
9.10.1

**Comment by vyakymenko** [comment]
Thanks for this issue, resolved.
