### ISSUE TITLE
Shared source between client and server?

### ISSUE THREAD

**Issue by redevill** [vyakymenko/angular-seed-express#147]
Is there interest in having some files in source code (e.g. interfaces) that could be used by both client and server?

The seed project manages the appropriate compilation/bundling to the server and client...
I have managed to create such a solution if there is interest.
Thanks
Eti

**Comment by vyakymenko** [comment]
Hello @redevil, 
Sure, you can create a PR with this feature,
Thanks!

**Comment by redevill** [comment]
Ok, will do, my Guess on procedure:

1. Make another branch with this feature, off of master.
2. Check in the new code.
3. Go to the pull request tab, create new pull request
4. select my branch in the example comparisons?

This right? Guideline document you would like me to follow?
Thanks
Eti

**Comment by vyakymenko** [comment]
Hello @redevill , please follow this [guide](https://github.com/vyakymenko/angular-seed-express/blob/master/.github/CONTRIBUTING.md).

Thanks!

**Comment by redevill** [comment]
Will do

**Comment by redevill** [comment]
Could use a little help. I have it working, with a problem, that is not ideal. There is a section in the config that allows you to specify systemJS and systemBuilder (same config used for both it seems?).

I have made the following spec:     name: 'shared/*', path: 'dist/tmp/shared/*'
The wild card (*) allows system builder to resolve the *.ts files that exist in the tmp folder when it does bundling. However, this same wild card, causes ambiguity in systemJS resolver, as it tries to resolve each entry in two ways. e.g. import { User } from 'shared/interfaces/user.interface'
is resolved as both "shared/interfaces/user.interface" and "shared/interfaces/user.interface.js". The one without the .js fails.

One solution is to change the import to be specific:
import { User } from 'shared/interfaces/user.interface.js'
This is not ideal - especially as older IDE's have problems with the "intellisense" in the typescript environment.

Ideas:
1. Separate Dev and Prod config, each for SystemJS and SystemBuilder?
2. Better path / map / package spec that works better?

Thoughts?
Thanks
Eti

**Comment by redevill** [comment]
Oh cool, what resolver will replace it? Webpack? So I can get familiar with how it works...

**Comment by vyakymenko** [comment]
There will be Rollup ;)

**Comment by vyakymenko** [comment]
I think that we can close this issue. The core is updated and now it's easy to manage client and server code.

**Comment by redevill** [comment]
Ok... so How do you share an interface, so that a single source file defines this interface for both the client and the server?

**Comment by vyakymenko** [comment]
Hi @redevill ,

I use something like this: ![Shared Interface](https://image.prntscr.com/image/f_gHDwsPTeSyFgSCKWWtCg.png)

**Comment by redevill** [comment]
Wow... how does that resolve in the dist folder? Do you have 2 copies?
When I tried that it did not work, because systemjs / systemjs-builder could not resolve both the relative import references. I also had similar resolution issues at run time.

Thank you, I will give the new code a try, with the above suggestion.

**Comment by redevill** [comment]
Speaking of new code...
I am still having much trouble with some libraries resolving, with version 6.0.1
Could really use a pointer in the right direction with this... If you could spare the time?
Should I open another issue?
![image](https://user-images.githubusercontent.com/8999255/46704189-18472600-cbe7-11e8-920d-73bd8d767fc8.png)

Thanks!

**Comment by vyakymenko** [comment]
Hi @redevil,

I hope that I’ll have some time at weekend and will provide you more details.
