### ISSUE TITLE
build.prod unsuccessful

### ISSUE THREAD

**Issue by kiranchowdhury** [vyakymenko/angular-seed-express#150]
Hello - 
I was trying to run build.prod, but it ended up with the following error -
[21:30:54] Error on fetch for rxjs/operators.js at file:///Users/kiranchowdhury/Documents/angular-seed-express/node_modules/rxjs/operators.js
	Loading @angular/core/bundles/core.umd.js
	Loading dist/tmp/app/main.js
	Error: ENOENT: no such file or directory, open '/Users/kiranchowdhury/Documents/angular-seed-express/node_modules/rxjs/operators.js'

However, build.dev runs successfully.

**Comment by vyakymenko** [comment]
@kiranchowdhury , issue resolved.
