### ISSUE TITLE
does angular 4.2.3 seed express supports  lazy loading feature on prod mode? If not how can we configure it

### ISSUE THREAD

**Issue by luckyvaishnav** [vyakymenko/angular-seed-express#180]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` =

**Comment by vyakymenko** [comment]
Hello @luckyvaishnav ,

Here is an example of (lazyLoading)[https://github.com/aelbore/ngx-seed]

**Comment by luckyvaishnav** [comment]
i am using 4.2.3 version of  angular-seed-express, do this code work in that?

**Comment by vyakymenko** [comment]
You can use old one to.
