### ISSUE TITLE
Dev vs Prod styling discrepancies

### ISSUE THREAD

**Issue by redevill** [vyakymenko/angular-seed-express#182]
This is for the latest release tag 6.0.1
[x ] bug report => search github for a similar issue or PR before submitting

**Current behavior**
npm run build.dev creates a non minified set of files, and runs perfectly in browser.
npm run build.prod currently appears to create a CSS with missing pieces
The symptom, is that the webpages are not styled correctly and FontAwsome icons missing.

**Expected behavior**
That the web page appears with the same styling in both dev and prod modes.

**Minimal reproduction of the problem with instructions**
As above, a project with bootstrap and fontawesome...

**What is the motivation / use case for changing the behavior?**
Huge motivation, going to have to roll back my project.

**Please tell us about your environment:**
Seed-express 6.0.1
Mac 10.13.6 (17G65)
Webstorm latest
Npm 6+
Node 9.10.1

Any pointers here would be really appreciated!! 
Thanks

**Comment by vyakymenko** [comment]
Thanks for this issue,

Will verify it at the new version of `angular-seed-express`.

**Comment by redevill** [comment]
@vyakymenko - The output file is not being minified (6.0.1) Even when I pull a blank seed project, and run "npm run build.prod.

Found a solution to my immediate problem. Bootstrap needs to go at the end, in the list of Project NPM Dependencies. Then it is placed at the end of the CSS, and does not disrupt other Styles.

 // Add `NPM` third-party libraries to be injected/bundled.
    // Source paths relative to node_modules folder.
    this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      {src: 'roboto-fontface/css/roboto/roboto-fontface.css', inject: true},
      {src: 'font-awesome/css/font-awesome.css', inject: true},
      {src: 'bootstrap/dist/css/bootstrap.min.css', inject: true}
    ];

**Comment by vyakymenko** [comment]
Thanks @redevill , I'll verify at the weekend!

**Comment by redevill** [comment]
@vyakymenko Thanks!

Narrowed it down a bit, something to do with the postcss step below:

If you change the css build task -> tools/tasks/seed/build.html_css.ts
Comment out the postcss processing, Then the CSS works
/**
 * Processes the external CSS files using `postcss` with the configured processors.
 */
function processExternalCss() {
  return getExternalCssStream()
    //.pipe(plugins.postcss(processors))
    .pipe(isProd ? plugins.concatCss(gulpConcatCssConfig.targetFile, gulpConcatCssConfig.options) : plugins.util.noop())
    .on('error', reportPostCssError)
    .pipe(gulp.dest(Config.CSS_DEST));
}

**Comment by vyakymenko** [comment]
Hi @redevill , 

The problem is that `postcss` can't process files that are **already contain prefixes** that is making compilation incorrect.

There are 2 solutions:
## You can use `scss` so that issue will not occur.
## Or you can comment `postcss` function as you mentioned if you still want to use `css`.

Thanks!
