### ISSUE TITLE
Server Side Testing? & Update support location? 

### ISSUE THREAD

**Issue by redevill** [vyakymenko/angular-seed-express#255]
[x ] feature request
[ x] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow]

First question - The support link is geared towards the root seed project, which has been deprecated. Is there an alternate forum for seed-express? Hence my second question...

Second - I see karma and Jasmine set up for client side tests? Was there an intended testing framework intended to be used for writing tests on the server side (Node.js testing)?

Appreciate any help 
Thanks
Eti

**Comment by vyakymenko** [comment]
@redevill , will add this in new https://github.com/vyakymenko/angular-express

**Comment by redevill** [comment]
Looks nice !! 
Looking forward to some info on server side tests?

**Comment by vyakymenko** [comment]
@redevill , I'll work on server side test very soon, hope will be implemented in `angular-express`

**Comment by vyakymenko** [comment]
@redevill , now [angular-express](https://github.com/vyakymenko/angular-express) support server side testing.

**Comment by redevill** [comment]
@vyakymenko - Awesome! Is the client side also mocha? or still Jasmine? 
We had some build issues (namespace collisions) between Mocha and Jasmine - when we tried mixing the two libraries.

We will be trying it out. Thanks for the hard work!

**Comment by vyakymenko** [comment]
@redevill , for client still Jasmine

**Comment by vyakymenko** [comment]
There are no collisions
