### ISSUE TITLE
Support for SSR - Server Side Rendering

### ISSUE THREAD

**Issue by bennykelly** [vyakymenko/angular-seed-express#49]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
App works perfectly, however, on load if you view the page source, you only get back the basic loading... div. Not great for social sharing or SEO.

**Expected behavior**
Ideally, utilizing server side rending (provided by the ServerModule in @angular/platform-server) the page would be served from the server initially and then transitioned to the browser code once downloaded. 

**Minimal reproduction of the problem with instructions**

Once the homepage loads, view source (not inspect) and you will see the DOM is not visible for the components 

**What is the motivation / use case for changing the behavior?**
Improves performance / time to first paint of page
Improved SEO and social sharing 

**Please tell us about your environment:**

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` = v6.11.1

**Comment by vyakymenko** [comment]
Hi @bennykelly , interesting feature, but at this point, you can use [Angular Universal](https://universal.angular.io/) that is resolving your issue. Please take a look more about it, 

Thanks!
