### ISSUE TITLE
how to use third party npm package which has .ts files 

### ISSUE THREAD

**Issue by rahulTiwari021** [vyakymenko/angular-seed-express#53]
hello i am using angular-seed-express version 2.1.2 and i have installed third party npm package which has .ts files in it but when i am trying to use that in my component it is not able to recognise the module

**Comment by vyakymenko** [comment]
Hi @rahulTiwari021 , do you have typings for this lib ?

**Comment by vyakymenko** [comment]
Please add typings to you config, so then you will be available to use your lib.
