### ISSUE TITLE
We are unable to build production for angular-seed-express 4.2.3

### ISSUE THREAD

**Issue by AbhijeetGiram** [vyakymenko/angular-seed-express#55]
I build production successfully, but  got this error in browser console.

VM83802 shims.js?1505822365078:1 Uncaught SyntaxError: Unexpected token <
VM83803 app.js?1505822365079:1 Uncaught SyntaxError: Unexpected token <

**Comment by vyakymenko** [comment]
Hi, @AbhijeetGiram , are you using the latest version? Any additional packages? OS?

**Comment by AbhijeetGiram** [comment]
Hello @vyakymenko 
OS: Windows 8
NPM: 4.2.0
Node: v6.9.4
Yes additional packages are there.
But I have solved it. I was unable to build production because of some path error in **"index.ts"** and it solved. 
BTW @vyakymenko 
does angular 4.2.3 seed express supports angular universal feature? If not how can we configure it.

**Comment by vyakymenko** [comment]
Hi @AbhijeetGiram , I think you need to read a little bit more about Angular Universal. It's a server-side rendering.
