### ISSUE TITLE
How can i build prod AOT?

### ISSUE THREAD

**Issue by AbhijeetGiram** [vyakymenko/angular-seed-express#56]
When I build.prod.aot, I got this error. How can i build prod AOT? Help me.

[14:22:49] Starting 'compile.ahead.prod'...
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 285:19 in the original .ts file), resolving symbol AppModule in D:/test_repo/c-next/dist/tmp/app/app.module.ts
    at positionalError (D:\test_repo\demo\node_modules\@angular\compiler\@angular\compiler.es5.js:25236:2)
Compilation failed

node: v6.9.4
npm: 4.2.0

Thanks

**Comment by vyakymenko** [comment]
Hi @AbhijeetGiram , I can't reproduce this issue on a clean clone of **angular-seed-express**.
