### ISSUE TITLE
gulp task "watch.dev" not working for backend code  which is in src/server directory.

### ISSUE THREAD

**Issue by AbhijeetGiram** [vyakymenko/angular-seed-express#58]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

watcher for backend code is not working. Need Help

Note: for front end code which is src/client directory, whenever i made any change "watch.dev" is working fine.
**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
OS: windows8

* **Angular Seed Version:** `4.2.3`

* **Node:** `node --version` = v6.9.4

**Comment by vyakymenko** [comment]
Thanks for finding this bug,
Watcher problem fixed, please update version of `angular-seed-express`.

For re-run, your newly built server changes, use daemon `pm2`.

**Comment by AbhijeetGiram** [comment]
@vyakymenko Thanks. It works fine now.
