### ISSUE TITLE
angular-seed-express 4.2.3 | got error when fire npm install command

### ISSUE THREAD

**Issue by AbhijeetGiram** [vyakymenko/angular-seed-express#61]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

[15:25:55] Error on fetch for rxjs/operators.js at file:///opt/atlassian/pipelines/agent/build/node_modules/rxjs/operators.js
	Loading rxjs/Rx.js
	Loading dist/tmp/app/shared/services/http/custom.http.js
	Loading dist/tmp/app/app.module.js
	Loading dist/tmp/app/main.js
	Error: ENOENT: no such file or directory, open '/opt/atlassian/pipelines/agent/build/node_modules/rxjs/operators.js'
    at Error (native)

Using  dependecy as:
"rxjs": "^5.2.0",

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
OS: windows8

* **Angular Seed Version:** `aaaaf75`
4.2.3

* **Node:** `node --version` = v6.9.4

**Comment by vyakymenko** [comment]
Hello @AbhijeetGiram, show me a piece of code where you use import operator, also you can try update to new version.

**Comment by vyakymenko** [comment]
@AbhijeetGiram , please delete `package-lock.json` and `node_modules/` directories and update to new version `4.4.4` that is live, this is very important, there was a hotfix for `rxjs`.

**Comment by AbhijeetGiram** [comment]
@vyakymenko Thanks.  rxjs: 5.4.3 works for me.
